[package]
name = "des-components"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
des-core = { path = "../des-core" }
des-metrics = { path = "../des-metrics" }
tokio = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
rand = { workspace = true }
rand_distr = { workspace = true }
rand_chacha = { workspace = true }
atomic-waker = "1.1"
uuid = { version = "1.19.0", features = ["v7", "serde", "v4"] }
tower = { version = "0.5", features = ["full"] }
tower-layer = "0.3"
# # tower-service = "0.3"
http = "1.0"
http-body = "1.0"
bytes = "1.0"
pin-project = "1.0"
futures = "0.3"

[dev-dependencies]
proptest = { workspace = true }
des-viz = { path = "../des-viz" }
plotters = { workspace = true }
