[package]
name = "des-metrics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
des-core = { path = "../des-core" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
# Standard metrics ecosystem
metrics = { workspace = true }
metrics-prometheus = { workspace = true }
hdrhistogram = { workspace = true }
quantiles = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
