[package]
name = "descartes-tonic-build"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "tonic code build helper for DesCartes"

[dependencies]
prost-build = "0.14.3"
heck = "0.5"
